version: '2'
services:
  time_server:
    build: ./time_server
    ports:
      - "3000:3000"
    depends_on: 
      - cache
  weather_server:
    build: ./weather_server
    ports:
      - "3001:3001"
    depends_on: 
      - cache
  cache:
    image: ddombrowsky/redis-with-health
    ports:
      - "6379:6379"